import { jsx as _jsx, jsxs as _jsxs } from "react/jsx-runtime";
import AdmissionHeader from './AdmissionHeader';
import AdmissionHero from './AdmissionHero';
import Marquee from './Marquee';
import UpdatedSyllabus from './UpdatedSyllabus';
import HolidayDetails from './HolidayDetails';
import Footer from './Footer';
import '../styles/Admission.css';
const Admission = ({ language, onBack, setCurrentPage }) => {
    const content = {
        en: {
            importantDates: 'IMPORTANT DATES',
            keyDates: 'KEY DATES FOR ADMISSION 2026 – 2027',
            applicationStart: 'Application Start',
            applicationDeadline: 'Application Deadline',
            meritList: 'Merit List Publication',
            classesBegin: 'Classes Begin',
            onlinePortal: 'Online application portal opens',
            lastDate: 'Last date to submit application',
            announcement: 'Selected candidates announcement',
            academicSession: 'Academic session starts',
            admissionProcess: 'ADMISSION PROCESS',
            stepByStep: 'STEP-BY-STEP GUIDE TO APPLY FOR ADMISSION',
            registerOnline: 'Register Online',
            visitAdmission: 'Visit the admission portal and create your account with your email and phone number.',
            fillApplication: 'Fill Application',
            completeForm: 'Complete the application form with all required personal and academic details.',
            uploadDocuments: 'Upload Documents',
            submitRequired: 'Submit all required documents in PDF format as per the specified requirements.',
            payFee: 'Pay Fee & Submit',
            completePayment: 'Complete the application fee payment and submit your application form.',
            requiredDocuments: 'REQUIRED DOCUMENTS',
            documentsNeeded: 'DOCUMENTS YOU NEED TO SUBMIT FOR ADMISSION',
            educationalCertificates: 'Educational Certificates',
            tenth: '10th and 12th standard mark sheets',
            graduation: 'Graduation degree certificate and mark sheet',
            migration: 'Migration certificate',
            character: 'Character certificate',
            identification: 'Identification & Personal Documents',
            aadhaar: 'Aadhar card copy',
            passport: 'Passport size photograph (4x6 cm)',
            birthCert: 'Birth certificate',
            caste: 'Caste certificate (if applicable)',
            addressProof: 'Address Proof',
            pasport: 'Passport or Aadhar card',
            voterId: 'Voter ID or Driving License',
            electricity: 'Electricity or Water Bill',
            rent: 'Rent agreement (if applicable)',
            additional: 'Additional Documents',
            entrance: 'Entrance exam scorecard (if applicable)',
            sports: 'Sports/Cultural achievement certificates',
            medical: 'Medical fitness certificate',
            gap: 'Gap affidavit (if applicable)',
            admissionCriteria: 'ADMISSION CRITERIA',
            eligibility: 'ELIGIBILITY AND SELECTION CRITERIA FOR VARIOUS PROGRAMS',
            bachelors: "Bachelor's Degree (B.A., B.Sc., B.Com)",
            bachelorEligibility: '12th Pass from recognized board',
            bachelorAge: 'No age limit',
            bachelorSelection: 'Merit-based on 12th marks',
            bachelorMinimum: '45% aggregate',
            masters: "Master's Degree (M.A., M.Sc., M.Com)",
            mastersEligibility: "Bachelor's degree in relevant field",
            mastersAge: 'No age limit',
            mastersSelection: 'Merit in Entrance Exam',
            mastersMinimum: '50% in graduation',
            phd: 'Ph.D. Program',
            phdEligibility: "Master's degree in relevant field",
            phdAge: 'No age limit',
            phdSelection: 'Interview & Research proposal',
            phdMinimum: "55% in master's",
            scholarships: 'SCHOLARSHIPS',
            scholarshipDesc: 'FINANCIAL AID AND SCHOLARSHIP OPPORTUNITIES'
        },
        hi: {
            importantDates: 'महत्वपूर्ण तारीखें',
            keyDates: 'प्रवेश 2026 - 2027 की मुख्य तारीखें',
            applicationStart: 'आवेदन शुरुआत',
            applicationDeadline: 'आवेदन की समय सीमा',
            meritList: 'योग्यता सूची प्रकाशन',
            classesBegin: 'कक्षाएं शुरू',
            onlinePortal: 'ऑनलाइन आवेदन पोर्टल खुलता है',
            lastDate: 'आवेदन जमा करने की अंतिम तारीख',
            announcement: 'चयनित उम्मीदवारों की घोषणा',
            academicSession: 'शैक्षणिक सत्र शुरू होता है',
            admissionProcess: 'प्रवेश प्रक्रिया',
            stepByStep: 'प्रवेश के लिए आवेदन करने के लिए चरण-दर-चरण मार्गदर्शन',
            registerOnline: 'ऑनलाइन पंजीकरण करें',
            visitAdmission: 'प्रवेश पोर्टल पर जाएं और अपने ईमेल और फोन नंबर से अपना खाता बनाएं।',
            fillApplication: 'आवेदन भरें',
            completeForm: 'आवेदन फॉर्म को सभी आवश्यक व्यक्तिगत और शैक्षणिक विवरण के साथ पूरा करें।',
            uploadDocuments: 'दस्तावेज अपलोड करें',
            submitRequired: 'निर्दिष्ट आवश्यकताओं के अनुसार सभी आवश्यक दस्तावेज PDF प्रारूप में जमा करें।',
            payFee: 'शुल्क का भुगतान करें और जमा करें',
            completePayment: 'आवेदन शुल्क का भुगतान पूरा करें और अपना आवेदन फॉर्म जमा करें।',
            requiredDocuments: 'आवश्यक दस्तावेज',
            documentsNeeded: 'प्रवेश के लिए जमा करने के लिए आवश्यक दस्तावेज',
            educationalCertificates: 'शैक्षणिक प्रमाणपत्र',
            tenth: '10वीं और 12वीं के मार्क शीट',
            graduation: 'स्नातक डिग्री प्रमाणपत्र और मार्क शीट',
            migration: 'स्थानांतरण प्रमाणपत्र',
            character: 'चरित्र प्रमाणपत्र',
            identification: 'पहचान और व्यक्तिगत दस्तावेज',
            aadhaar: 'आधार कार्ड की प्रति',
            passport: 'पासपोर्ट आकार की तस्वीर (4x6 सेमी)',
            birthCert: 'जन्म प्रमाणपत्र',
            caste: 'जाति प्रमाणपत्र (यदि लागू हो)',
            addressProof: 'पता प्रमाण',
            pasport: 'पासपोर्ट या आधार कार्ड',
            voterId: 'मतदाता पहचान पत्र या ड्राइविंग लाइसेंस',
            electricity: 'बिजली या पानी का बिल',
            rent: 'किराया समझौता (यदि लागू हो)',
            additional: 'अतिरिक्त दस्तावेज',
            entrance: 'प्रवेश परीक्षा स्कोरकार्ड (यदि लागू हो)',
            sports: 'खेल/सांस्कृतिक उपलब्धि प्रमाणपत्र',
            medical: 'चिकित्सा फिटनेस प्रमाणपत्र',
            gap: 'गैप शपथपत्र (यदि लागू हो)',
            admissionCriteria: 'प्रवेश मानदंड',
            eligibility: 'विभिन्न कार्यक्रमों के लिए पात्रता और चयन मानदंड',
            bachelors: 'स्नातक डिग्री (बी.ए., बी.एससी., बी.कॉम)',
            bachelorEligibility: 'मान्यता प्राप्त बोर्ड से 12वीं पास',
            bachelorAge: 'कोई आयु सीमा नहीं',
            bachelorSelection: '12वीं अंकों के आधार पर योग्यता',
            bachelorMinimum: '45% कुल',
            masters: 'मास्टर डिग्री (एम.ए., एम.एससी., एम.कॉम)',
            mastersEligibility: 'प्रासंगिक क्षेत्र में स्नातक डिग्री',
            mastersAge: 'कोई आयु सीमा नहीं',
            mastersSelection: 'प्रवेश परीक्षा में योग्यता',
            mastersMinimum: 'स्नातकोत्तर में 50%',
            phd: 'पीएच.डी. कार्यक्रम',
            phdEligibility: 'प्रासंगिक क्षेत्र में मास्टर डिग्री',
            phdAge: 'कोई आयु सीमा नहीं',
            phdSelection: 'साक्षात्कार और अनुसंधान प्रस्ताव',
            phdMinimum: "मास्टर में 55%",
            scholarships: 'छात्रवृत्तियां',
            scholarshipDesc: 'वित्तीय सहायता और छात्रवृत्ति के अवसर'
        }
    };
    const data = content[language];
    return (_jsxs("div", { className: "admission-page", children: [_jsx(Marquee, { language: language }), _jsx(AdmissionHeader, { language: language, onBack: onBack }), _jsx(AdmissionHero, { language: language }), _jsx("section", { className: "important-dates", children: _jsxs("div", { className: "section-container", children: [_jsx("h1", { children: data.importantDates }), _jsx("p", { className: "section-subtitle", children: data.keyDates }), _jsxs("div", { className: "dates-grid", children: [_jsxs("div", { className: "date-card", children: [_jsx("div", { className: "date-icon", children: "\uD83D\uDCC5" }), _jsx("h3", { children: data.applicationStart }), _jsx("p", { className: "date-value", children: "January 15, 2026" }), _jsx("p", { className: "date-description", children: data.onlinePortal })] }), _jsxs("div", { className: "date-card", children: [_jsx("div", { className: "date-icon", children: "\uD83D\uDCCB" }), _jsx("h3", { children: data.applicationDeadline }), _jsx("p", { className: "date-value", children: "May 31, 2026" }), _jsx("p", { className: "date-description", children: data.lastDate })] }), _jsxs("div", { className: "date-card", children: [_jsx("div", { className: "date-icon", children: "\u2713" }), _jsx("h3", { children: data.meritList }), _jsx("p", { className: "date-value", children: "June 30, 2026" }), _jsx("p", { className: "date-description", children: data.announcement })] }), _jsxs("div", { className: "date-card", children: [_jsx("div", { className: "date-icon", children: "\uD83C\uDF93" }), _jsx("h3", { children: data.classesBegin }), _jsx("p", { className: "date-value", children: "August 1, 2026" }), _jsx("p", { className: "date-description", children: data.academicSession })] })] })] }) }), _jsx("section", { className: "admission-process", children: _jsxs("div", { className: "section-container", children: [_jsx("h1", { children: data.admissionProcess }), _jsx("p", { className: "section-subtitle", children: data.stepByStep }), _jsxs("div", { className: "process-grid", children: [_jsxs("div", { className: "process-card", children: [_jsx("div", { className: "process-number", children: "1" }), _jsx("h3", { children: data.registerOnline }), _jsx("p", { children: data.visitAdmission })] }), _jsxs("div", { className: "process-card", children: [_jsx("div", { className: "process-number", children: "2" }), _jsx("h3", { children: data.fillApplication }), _jsx("p", { children: data.completeForm })] }), _jsxs("div", { className: "process-card", children: [_jsx("div", { className: "process-number", children: "3" }), _jsx("h3", { children: data.uploadDocuments }), _jsx("p", { children: data.submitRequired })] }), _jsxs("div", { className: "process-card", children: [_jsx("div", { className: "process-number", children: "4" }), _jsx("h3", { children: data.payFee }), _jsx("p", { children: data.completePayment })] })] })] }) }), _jsx("section", { className: "required-documents", children: _jsxs("div", { className: "section-container", children: [_jsx("h1", { children: data.requiredDocuments }), _jsx("p", { className: "section-subtitle", children: data.documentsNeeded }), _jsxs("div", { className: "documents-grid", children: [_jsxs("div", { className: "document-card", children: [_jsx("div", { className: "doc-icon", children: "\uD83D\uDCC4" }), _jsx("h3", { children: data.educationalCertificates }), _jsxs("ul", { children: [_jsxs("li", { children: ["\u2713 ", data.tenth] }), _jsxs("li", { children: ["\u2713 ", data.graduation] }), _jsxs("li", { children: ["\u2713 ", data.migration] }), _jsxs("li", { children: ["\u2713 ", data.character] })] })] }), _jsxs("div", { className: "document-card", children: [_jsx("div", { className: "doc-icon", children: "\uD83C\uDD94" }), _jsx("h3", { children: data.identification }), _jsxs("ul", { children: [_jsxs("li", { children: ["\u2713 ", data.aadhaar] }), _jsxs("li", { children: ["\u2713 ", data.passport] }), _jsxs("li", { children: ["\u2713 ", data.birthCert] }), _jsxs("li", { children: ["\u2713 ", data.caste] })] })] }), _jsxs("div", { className: "document-card", children: [_jsx("div", { className: "doc-icon", children: "\uD83C\uDFE0" }), _jsx("h3", { children: data.addressProof }), _jsxs("ul", { children: [_jsxs("li", { children: ["\u2713 ", data.pasport] }), _jsxs("li", { children: ["\u2713 ", data.voterId] }), _jsxs("li", { children: ["\u2713 ", data.electricity] }), _jsxs("li", { children: ["\u2713 ", data.rent] })] })] }), _jsxs("div", { className: "document-card", children: [_jsx("div", { className: "doc-icon", children: "\uD83C\uDF96\uFE0F" }), _jsx("h3", { children: data.additional }), _jsxs("ul", { children: [_jsxs("li", { children: ["\u2713 ", data.entrance] }), _jsxs("li", { children: ["\u2713 ", data.sports] }), _jsxs("li", { children: ["\u2713 ", data.medical] }), _jsxs("li", { children: ["\u2713 ", data.gap] })] })] })] })] }) }), _jsx("section", { className: "admission-criteria", children: _jsxs("div", { className: "section-container", children: [_jsx("h1", { children: data.admissionCriteria }), _jsx("p", { className: "section-subtitle", children: data.eligibility }), _jsxs("div", { className: "criteria-grid", children: [_jsxs("div", { className: "criteria-card", children: [_jsx("h3", { children: data.bachelors }), _jsxs("div", { className: "criteria-details", children: [_jsxs("p", { children: [_jsx("strong", { children: "Eligibility:" }), " ", data.bachelorEligibility] }), _jsxs("p", { children: [_jsx("strong", { children: "Age Limit:" }), " ", data.bachelorAge] }), _jsxs("p", { children: [_jsx("strong", { children: "Selection:" }), " ", data.bachelorSelection] }), _jsxs("p", { children: [_jsx("strong", { children: "Minimum %:" }), " ", data.bachelorMinimum] })] })] }), _jsxs("div", { className: "criteria-card", children: [_jsx("h3", { children: data.masters }), _jsxs("div", { className: "criteria-details", children: [_jsxs("p", { children: [_jsx("strong", { children: "Eligibility:" }), " ", data.mastersEligibility] }), _jsxs("p", { children: [_jsx("strong", { children: "Age Limit:" }), " ", data.mastersAge] }), _jsxs("p", { children: [_jsx("strong", { children: "Selection:" }), " ", data.mastersSelection] }), _jsxs("p", { children: [_jsx("strong", { children: "Minimum %:" }), " ", data.mastersMinimum] })] })] }), _jsxs("div", { className: "criteria-card", children: [_jsx("h3", { children: data.phd }), _jsxs("div", { className: "criteria-details", children: [_jsxs("p", { children: [_jsx("strong", { children: "Eligibility:" }), " ", data.phdEligibility] }), _jsxs("p", { children: [_jsx("strong", { children: "Age Limit:" }), " ", data.phdAge] }), _jsxs("p", { children: [_jsx("strong", { children: "Selection:" }), " ", data.phdSelection] }), _jsxs("p", { children: [_jsx("strong", { children: "Minimum %:" }), " ", data.phdMinimum] })] })] })] })] }) }), _jsx(UpdatedSyllabus, { language: language }), _jsx(HolidayDetails, { language: language }), _jsx(Footer, { language: language, setCurrentPage: setCurrentPage })] }));
};
export default Admission;
//# sourceMappingURL=Admission.js.map