import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import '../styles/PolicyPages.css';
const IPRPolicy = ({ language, onBack, onHome }) => {
    return (_jsxs("div", { className: "policy-page", children: [_jsxs("div", { className: "navigation-buttons", children: [_jsxs("button", { className: "back-button", onClick: onBack, children: ["\u2190 ", language === 'en' ? 'Back' : 'पीछे'] }), _jsxs("button", { className: "home-button", onClick: onHome || onBack, children: ["\uD83C\uDFE0 ", language === 'en' ? 'Home' : 'होम'] })] }), _jsxs("div", { className: "policy-container", children: [_jsxs("div", { className: "policy-header", children: [_jsx("h1", { children: language === 'en' ? 'IPR Policy 2022' : 'बौद्धिक संपत्ति अधिकार नीति 2022' }), _jsx("p", { children: language === 'en' ? 'Protection and Management of Intellectual Property' : 'बौद्धिक संपत्ति की सुरक्षा और प्रबंधन' })] }), _jsxs("div", { className: "policy-content", children: [_jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Purpose' : 'उद्देश्य' }), _jsx("p", { children: language === 'en'
                                            ? 'The IPR Policy 2022 is designed to foster innovation, protect intellectual property rights, and ensure fair ownership and benefit-sharing of innovations created by faculty, researchers, and students.'
                                            : 'बौद्धिक संपत्ति अधिकार नीति 2022 नवाचार को प्रोत्साहित करने, बौद्धिक संपत्ति अधिकारों की सुरक्षा, और न्यायसंगत स्वामित्व सुनिश्चित करने के लिए डिजाइन की गई है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Types of IP Protected' : 'IP की सुरक्षित प्रकार' }), _jsxs("ul", { className: "provisions-list", children: [_jsx("li", { children: language === 'en' ? 'Patents and Inventions' : 'पेटेंट और आविष्कार' }), _jsx("li", { children: language === 'en' ? 'Copyrights and Literary Works' : 'कॉपीराइट और साहित्यिक कार्य' }), _jsx("li", { children: language === 'en' ? 'Trademarks and Brand Names' : 'ट्रेडमार्क और ब्रांड नाम' }), _jsx("li", { children: language === 'en' ? 'Design Patents' : 'डिजाइन पेटेंट' }), _jsx("li", { children: language === 'en' ? 'Trade Secrets and Confidential Information' : 'व्यापार रहस्य और गोपनीय जानकारी' }), _jsx("li", { children: language === 'en' ? 'Databases and Software' : 'डेटाबेस और सॉफ्टवेयर' })] })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Ownership and Rights' : 'स्वामित्व और अधिकार' }), _jsx("p", { children: language === 'en'
                                            ? 'The policy clearly defines ownership of IP created during the course of employment, research, or use of university facilities. It establishes fair mechanisms for revenue sharing and benefit allocation among creators and the institution.'
                                            : 'यह नीति विश्वविद्यालय सुविधाओं के उपयोग के दौरान बनाई गई IP के स्वामित्व को स्पष्ट रूप से परिभाषित करती है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Patent Application Support' : 'पेटेंट आवेदन समर्थन' }), _jsx("p", { children: language === 'en'
                                            ? 'The university provides financial and legal support for filing patent applications. An IPR Cell assists inventors in documenting, evaluating, and pursuing patent protection for innovative inventions.'
                                            : 'विश्वविद्यालय पेटेंट आवेदन दाखिल करने के लिए वित्तीय और कानूनी समर्थन प्रदान करता है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Commercialization and Licensing' : 'व्यावसायीकरण और लाइसेंसिंग' }), _jsx("p", { children: language === 'en'
                                            ? 'The institution has mechanisms for licensing and commercializing IP for benefit of inventors, society, and the university. Technology transfer agreements help translate research innovations into commercial benefits.'
                                            : 'संस्थान के पास IP के व्यावसायीकरण के लिए तंत्र है जो आविष्कारकों, समाज और विश्वविद्यालय के लाभ के लिए है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Dispute Resolution' : 'विवाद समाधान' }), _jsx("p", { children: language === 'en'
                                            ? 'The policy includes procedures for resolving disputes related to IP ownership, authorship, and benefit sharing. An IPR Cell committee reviews disputes and provides fair resolution mechanisms.'
                                            : 'यह नीति IP स्वामित्व, लेखकत्व और लाभ साझाकरण से संबंधित विवादों को हल करने के लिए प्रक्रियाएं शामिल करती है।' })] })] })] })] }));
};
export default IPRPolicy;
//# sourceMappingURL=IPRPolicy.js.map