import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import '../styles/PolicyPages.css';
const IQACPage = ({ language, onBack, onHome }) => {
    return (_jsxs("div", { className: "policy-page", children: [_jsxs("div", { className: "navigation-buttons", children: [_jsxs("button", { className: "back-button", onClick: onBack, children: ["\u2190 ", language === 'en' ? 'Back' : 'पीछे'] }), _jsxs("button", { className: "home-button", onClick: onHome || onBack, children: ["\uD83C\uDFE0 ", language === 'en' ? 'Home' : 'होम'] })] }), _jsxs("div", { className: "policy-container", children: [_jsxs("div", { className: "policy-header", children: [_jsx("h1", { children: language === 'en' ? 'Internal Quality Assurance Cell' : 'आंतरिक गुणवत्ता आश्वासन सेल' }), _jsx("p", { children: language === 'en' ? 'Ensuring Academic Excellence and Continuous Improvement' : 'शैक्षणिक उत्कृष्टता और निरंतर सुधार सुनिश्चित करना' })] }), _jsxs("div", { className: "policy-content", children: [_jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Mission' : 'मिशन' }), _jsx("p", { children: language === 'en'
                                            ? 'The Internal Quality Assurance Cell (IQAC) is committed to ensuring academic quality and institutional excellence by monitoring, evaluating, and facilitating continuous improvement in all academic and administrative functions.'
                                            : 'आंतरिक गुणवत्ता आश्वासन सेल (IQAC) सभी शैक्षणिक और प्रशासनिक कार्यों में निगरानी, मूल्यांकन और निरंतर सुधार की सुविधा देकर शैक्षणिक गुणवत्ता और संस्थागत उत्कृष्टता सुनिश्चित करने के लिए प्रतिबद्ध है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Key Functions' : 'मुख्य कार्य' }), _jsxs("ul", { className: "provisions-list", children: [_jsx("li", { children: language === 'en' ? 'Development of quality benchmarks and standards' : 'गुणवत्ता मानकों और मानदंडों का विकास' }), _jsx("li", { children: language === 'en' ? 'Monitoring of teaching-learning processes' : 'शिक्षण-अधिगम प्रक्रियाओं की निगरानी' }), _jsx("li", { children: language === 'en' ? 'Student feedback collection and analysis' : 'छात्र प्रतिक्रिया संग्रह और विश्लेषण' }), _jsx("li", { children: language === 'en' ? 'Faculty development programs' : 'संकाय विकास कार्यक्रम' }), _jsx("li", { children: language === 'en' ? 'Research and innovation promotion' : 'अनुसंधान और नवाचार प्रोत्साहन' }), _jsx("li", { children: language === 'en' ? 'Infrastructure assessment and improvement' : 'बुनियादी ढांचे का आकलन और सुधार' }), _jsx("li", { children: language === 'en' ? 'Compliance monitoring with accreditation standards' : 'मान्यता मानकों के साथ अनुपालन निगरानी' })] })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Quality Indicators' : 'गुणवत्ता संकेतक' }), _jsx("p", { children: language === 'en'
                                            ? 'IQAC monitors various quality indicators including curriculum design, teaching methodology, student engagement, assessment methods, faculty qualifications, and institutional infrastructure.'
                                            : 'IQAC पाठ्यक्रम डिजाइन, शिक्षण पद्धति, छात्र जुड़ाव, मूल्यांकन विधियों, संकाय योग्यता और संस्थागत बुनियादी ढांचे सहित विभिन्न गुणवत्ता संकेतकों की निगरानी करता है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Accreditation and Assessment' : 'मान्यता और मूल्यांकन' }), _jsx("p", { children: language === 'en'
                                            ? 'IQAC facilitates the university\'s accreditation process with NAAC (National Assessment and Accreditation Council) and conducts internal assessments to ensure compliance with national and international quality standards.'
                                            : 'IQAC विश्वविद्यालय की NAAC (राष्ट्रीय मूल्यांकन और मान्यता परिषद) के साथ मान्यता प्रक्रिया की सुविधा देता है और राष्ट्रीय और अंतर्राष्ट्रीय गुणवत्ता मानकों के अनुपालन को सुनिश्चित करने के लिए आंतरिक मूल्यांकन करता है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Stakeholder Engagement' : 'हितधारक जुड़ाव' }), _jsx("p", { children: language === 'en'
                                            ? 'IQAC involves students, faculty, parents, and employers in quality assurance initiatives through feedback mechanisms, surveys, and stakeholder committees to ensure comprehensive institutional improvement.'
                                            : 'IQAC प्रतिक्रिया तंत्र, सर्वेक्षण और हितधारक समितियों के माध्यम से गुणवत्ता आश्वासन पहल में छात्रों, संकाय, माता-पिता और नियोक्ताओं को शामिल करता है।' })] })] })] })] }));
};
export default IQACPage;
//# sourceMappingURL=IQACPage.js.map