import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import '../styles/PolicyPages.css';
const ITPolicy = ({ language, onBack, onHome }) => {
    return (_jsxs("div", { className: "policy-page", children: [_jsxs("div", { className: "navigation-buttons", children: [_jsxs("button", { className: "back-button", onClick: onBack, children: ["\u2190 ", language === 'en' ? 'Back' : 'पीछे'] }), _jsxs("button", { className: "home-button", onClick: onHome || onBack, children: ["\uD83C\uDFE0 ", language === 'en' ? 'Home' : 'होम'] })] }), _jsxs("div", { className: "policy-container", children: [_jsxs("div", { className: "policy-header", children: [_jsx("h1", { children: language === 'en' ? 'IT Policy 2022' : 'आईटी नीति 2022' }), _jsx("p", { children: language === 'en' ? 'Digital Transformation and Technology Integration' : 'डिजिटल परिवर्तन और प्रौद्योगिकी एकीकरण' })] }), _jsxs("div", { className: "policy-content", children: [_jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Policy Objectives' : 'नीति उद्देश्य' }), _jsx("p", { children: language === 'en'
                                            ? 'The IT Policy 2022 aims to leverage digital technology for improved academic delivery, administrative efficiency, and institutional governance while ensuring data security and cyber safety.'
                                            : 'आईटी नीति 2022 का उद्देश्य बेहतर शैक्षणिक वितरण, प्रशासनिक दक्षता और संस्थागत शासन के लिए डिजिटल प्रौद्योगिकी का लाभ उठाना है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Key Areas' : 'मुख्य क्षेत्र' }), _jsxs("ul", { className: "provisions-list", children: [_jsx("li", { children: language === 'en' ? 'Digital Learning Infrastructure' : 'डिजिटल सीखने की बुनियादी ढांचा' }), _jsx("li", { children: language === 'en' ? 'Cloud Computing and Data Centers' : 'क्लाउड कंप्यूटिंग और डेटा केंद्र' }), _jsx("li", { children: language === 'en' ? 'Cybersecurity Framework' : 'साइबर सुरक्षा ढांचा' }), _jsx("li", { children: language === 'en' ? 'Administrative Management Systems' : 'प्रशासनिक प्रबंधन प्रणाली' }), _jsx("li", { children: language === 'en' ? 'Open Source Software Adoption' : 'ओपन सोर्स सॉफ्टवेयर अपनाना' }), _jsx("li", { children: language === 'en' ? 'Mobile Application Development' : 'मोबाइल एप्लिकेशन विकास' }), _jsx("li", { children: language === 'en' ? 'IT Governance and Compliance' : 'आईटी शासन और अनुपालन' })] })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Digital Learning' : 'डिजिटल सीखना' }), _jsx("p", { children: language === 'en'
                                            ? 'The policy promotes blended and online learning using Learning Management Systems (LMS), digital content repositories, and interactive educational technology to enhance student engagement and learning outcomes.'
                                            : 'यह नीति सीखने वाली प्रबंधन प्रणाली (LMS) का उपयोग करके मिश्रित और ऑनलाइन सीखने को बढ़ावा देती है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Data Security and Privacy' : 'डेटा सुरक्षा और गोपनीयता' }), _jsx("p", { children: language === 'en'
                                            ? 'Strong emphasis on data protection, encryption, access control, and privacy compliance. Regular security audits and cyber awareness training for staff and students ensure robust protection of university data.'
                                            : 'डेटा सुरक्षा, एन्क्रिप्शन, पहुंच नियंत्रण और गोपनीयता अनुपालन पर जोर दिया गया है। नियमित सुरक्षा ऑडिट विश्वविद्यालय डेटा की मजबूत सुरक्षा सुनिश्चित करते हैं।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Capacity Building' : 'क्षमता निर्माण' }), _jsx("p", { children: language === 'en'
                                            ? 'Regular IT training programs, workshops, and professional development initiatives for faculty and staff to enhance digital literacy and effective utilization of technology in academic and administrative processes.'
                                            : 'संकाय और कर्मचारियों के लिए नियमित आईटी प्रशिक्षण कार्यक्रम और व्यावसायिक विकास पहल डिजिटल साक्षरता बढ़ाने के लिए।' })] })] })] })] }));
};
export default ITPolicy;
//# sourceMappingURL=ITPolicy.js.map