import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import '../styles/PolicyPages.css';
const RTIAct = ({ language, onBack, onHome }) => {
    return (_jsxs("div", { className: "policy-page", children: [_jsxs("div", { className: "navigation-buttons", children: [_jsxs("button", { className: "back-button", onClick: onBack, children: ["\u2190 ", language === 'en' ? 'Back' : 'पीछे'] }), _jsxs("button", { className: "home-button", onClick: onHome || onBack, children: ["\uD83C\uDFE0 ", language === 'en' ? 'Home' : 'होम'] })] }), _jsxs("div", { className: "policy-container", children: [_jsxs("div", { className: "policy-header", children: [_jsx("h1", { children: language === 'en' ? 'Right to Information Act (RTI)' : 'सूचना का अधिकार अधिनियम (आरटीआई)' }), _jsx("p", { children: language === 'en' ? 'Transparency and Accountability in Governance' : 'शासन में पारदर्शिता और जवाबदेही' })] }), _jsxs("div", { className: "policy-content", children: [_jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'What is RTI?' : 'आरटीआई क्या है?' }), _jsx("p", { children: language === 'en'
                                            ? 'The Right to Information (RTI) Act, 2005 is a Central legislation that empowers all citizens and institutions to seek information held by public authorities, including universities. It promotes transparency and accountability in governance.'
                                            : 'सूचना का अधिकार (आरटीआई) अधिनियम, 2005 एक केंद्रीय कानून है जो सभी नागरिकों और संस्थानों को सार्वजनिक प्राधिकारों द्वारा रखी गई जानकारी मांगने का अधिकार देता है। यह शासन में पारदर्शिता और जवाबदेही को बढ़ावा देता है।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Scope and Coverage' : 'दायरा और कवरेज' }), _jsx("p", { children: language === 'en'
                                            ? 'Sri Dev Suman Uttarakhand University being a public institution is subject to RTI Act. Citizens can request information about university operations, budget allocation, admissions, academic programs, and administrative decisions.'
                                            : 'श्री देव सुमन उत्तरांचल विश्वविद्यालय होने के नाते एक सार्वजनिक संस्थान आरटीआई अधिनियम के अधीन है। नागरिक विश्वविद्यालय संचालन, बजट आवंटन, प्रवेश, शैक्षणिक कार्यक्रमों और प्रशासनिक निर्णयों के बारे में जानकारी का अनुरोध कर सकते हैं।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'How to File an RTI Request' : 'आरटीआई अनुरोध कैसे दाखिल करें' }), _jsxs("ol", { className: "procedures-list", children: [_jsx("li", { children: language === 'en' ? 'Submit the request in writing to the Central Public Information Officer (CPIO)' : 'केंद्रीय सार्वजनिक सूचना अधिकारी (CPIO) को लिखित रूप में अनुरोध प्रस्तुत करें' }), _jsx("li", { children: language === 'en' ? 'Include clear description of information required' : 'आवश्यक जानकारी का स्पष्ट विवरण शामिल करें' }), _jsx("li", { children: language === 'en' ? 'Pay the prescribed fee (if applicable)' : 'निर्धारित शुल्क का भुगतान करें (यदि लागू हो)' }), _jsx("li", { children: language === 'en' ? 'CPIO will respond within 30 days' : 'CPIO 30 दिनों के भीतर जवाब देगा' }), _jsx("li", { children: language === 'en' ? 'Appeal to First Appellate Authority if unsatisfied' : 'असंतुष्ट होने पर प्रथम अपीलीय प्राधिकारी के पास अपील करें' })] })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Information Exemptions' : 'सूचना छूट' }), _jsx("p", { children: language === 'en'
                                            ? 'Some information may be exempted from disclosure as per RTI Act Section 8 and 9, including security matters, personal information, information affecting national interest, etc.'
                                            : 'आरटीआई अधिनियम की धारा 8 और 9 के अनुसार कुछ सूचना प्रकटीकरण से छूट प्राप्त हो सकती है, जिसमें सुरक्षा मामले, व्यक्तिगत जानकारी, राष्ट्रीय हित को प्रभावित करने वाली जानकारी आदि शामिल हैं।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'University CPIO Details' : 'विश्वविद्यालय CPIO विवरण' }), _jsx("p", { children: language === 'en'
                                            ? 'For filing RTI requests to Sri Dev Suman Uttarakhand University, please contact the designated Central Public Information Officer (CPIO) at the university administration office during working hours.'
                                            : 'श्री देव सुमन उत्तरांचल विश्वविद्यालय के लिए आरटीआई अनुरोध दाखिल करने के लिए, कार्य के घंटों के दौरान विश्वविद्यालय प्रशासन कार्यालय में नामित केंद्रीय सार्वजनिक सूचना अधिकारी (CPIO) से संपर्क करें।' })] })] })] })] }));
};
export default RTIAct;
//# sourceMappingURL=RTIAct.js.map