import { jsxs as _jsxs, jsx as _jsx } from "react/jsx-runtime";
import '../styles/PolicyPages.css';
const StartupCell = ({ language, onBack, onHome }) => {
    return (_jsxs("div", { className: "policy-page", children: [_jsxs("div", { className: "navigation-buttons", children: [_jsxs("button", { className: "back-button", onClick: onBack, children: ["\u2190 ", language === 'en' ? 'Back' : 'पीछे'] }), _jsxs("button", { className: "home-button", onClick: onHome || onBack, children: ["\uD83C\uDFE0 ", language === 'en' ? 'Home' : 'होम'] })] }), _jsxs("div", { className: "policy-container", children: [_jsxs("div", { className: "policy-header", children: [_jsx("h1", { children: language === 'en' ? 'Startup Cell & Incubation Center' : 'स्टार्टअप सेल और इनक्यूबेशन केंद्र' }), _jsx("p", { children: language === 'en' ? 'Fostering Entrepreneurship and Innovation' : 'उद्यमिता और नवाचार को बढ़ावा देना' })] }), _jsxs("div", { className: "policy-content", children: [_jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Overview' : 'अवलोकन' }), _jsx("p", { children: language === 'en'
                                            ? 'The Startup Cell & Incubation Center is dedicated to nurturing entrepreneurial ideas and transforming them into viable business ventures. We provide mentorship, funding support, and infrastructure to budding entrepreneurs.'
                                            : 'स्टार्टअप सेल और इनक्यूबेशन केंद्र उद्यमशील विचारों को पोषित करने और उन्हें व्यवहार्य व्यावसायिक उद्यमों में बदलने के लिए समर्पित है। हम हमारे उद्यमशील युवा उद्यमियों को मार्गदर्शन, financial सहायता और बुनियादी ढांचा प्रदान करते हैं।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Services Offered' : 'प्रदान की गई सेवाएं' }), _jsxs("ul", { className: "provisions-list", children: [_jsx("li", { children: language === 'en' ? 'Business Ideation and Validation' : 'व्यावसायिक विचार और मान्यता' }), _jsx("li", { children: language === 'en' ? 'Business Plan Development' : 'व्यावसायिक योजना विकास' }), _jsx("li", { children: language === 'en' ? 'Mentorship from Industry Experts' : 'उद्योग विशेषज्ञों से मार्गदर्शन' }), _jsx("li", { children: language === 'en' ? 'Funding and Financial Assistance' : 'फंडिंग और वित्तीय सहायता' }), _jsx("li", { children: language === 'en' ? 'Workspace and Lab Facilities' : 'कार्यस्थान और प्रयोगशाला सुविधाएं' }), _jsx("li", { children: language === 'en' ? 'Networking with Investors and Partners' : 'निवेशकों और भागीदारों के साथ नेटवर्किंग' }), _jsx("li", { children: language === 'en' ? 'Legal and Compliance Support' : 'कानूनी और अनुपालन समर्थन' })] })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Incubation Programs' : 'इनक्यूबेशन कार्यक्रम' }), _jsx("p", { children: language === 'en'
                                            ? 'We offer structured incubation programs of 6-12 months duration designed to help startups achieve key milestones, validate their business model, and prepare for scaling and investment.'
                                            : 'हम 6-12 महीने की अवधि के संरचित इनक्यूबेशन कार्यक्रम प्रदान करते हैं जो स्टार्टअप को सफल होने में मदद करते हैं।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'Success Stories' : 'सफलता की कहानियां' }), _jsx("p", { children: language === 'en'
                                            ? 'Several startups incubated at our center have successfully secured seed funding, launched their products, and created employment opportunities. Our alumni entrepreneurs are making significant contributions to their respective industries.'
                                            : 'हमारे केंद्र में इनक्यूबेट किए गए कई स्टार्टअप्स को सीड फंडिंग सुरक्षित हुई है, उन्होंने अपने उत्पाद लॉन्च किए हैं और रोजगार के अवसर सृजित किए हैं।' })] }), _jsxs("section", { className: "content-section", children: [_jsx("h2", { children: language === 'en' ? 'How to Apply' : 'आवेदन कैसे करें' }), _jsx("p", { children: language === 'en'
                                            ? 'If you have an innovative business idea and want to transform it into a startup, please contact the Startup Cell for application details, eligibility criteria, and selection process.'
                                            : 'यदि आपके पास एक नवीन व्यावसायिक विचार है और इसे स्टार्टअप में बदलना चाहते हैं, तो आवेदन विवरण, पात्रता मानदंड और चयन प्रक्रिया के लिए स्टार्टअप सेल से संपर्क करें।' })] })] })] })] }));
};
export default StartupCell;
//# sourceMappingURL=StartupCell.js.map